### PR TITLE
update

### PR DESCRIPTION
**Pull request by ngwako-dev**

### CODE REVIEW

**Review by darrenferreira — COMMENTED** [review]
Hi @ngwako-dev please have a read about .gitignore files. You should never ever commit the following files to a git repo:

*.iml
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build
/captures
.externalNativeBuild
.idea/


Add a .gitignore file and include the above mentioned lines in the file.

**Review by KevashanGovender — CHANGES_REQUESTED** [review]
Please use more descriptive commit messages [https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9](good commit message etiquette)

**Review by darrenferreira — COMMENTED** [review]
hey man, it seems the .gitignore is not working due to the incorrect naming of the file :)

**Comment by ngwako-dev** [comment]
Thanks for the update

**Review by darrenferreira — CHANGES_REQUESTED** [review]
Please remove this branch, add your .gitignore and file changes

**Pull request closed without merging**
